import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CANONICAL = ROOT / ".ai-workflow" / "canonical"
MARKER_RE = re.compile(
    r"^<!-- Generated by ai-workflow ([^;]+); source-sha256: ([0-9a-f]{64}) -->$"
)
PROVIDERS = {
    "codex": {
        "instruction": ROOT / "AGENTS.md",
        "skills": ROOT / ".agents" / "skills",
        "replacements": {
            "{{INSTRUCTION_FILE}}": "AGENTS.md",
            "{{PROVIDER_NAME}}": "Codex",
            "{{PROVIDER_CONFIG_DIR}}": ".codex",
            "{{SETTINGS_SURFACE}}": "~/.codex/config.toml and the host approval policy",
        },
    },
    "claude": {
        "instruction": ROOT / "CLAUDE.md",
        "skills": ROOT / ".claude" / "skills",
        "replacements": {
            "{{INSTRUCTION_FILE}}": "CLAUDE.md",
            "{{PROVIDER_NAME}}": "Claude Code",
            "{{PROVIDER_CONFIG_DIR}}": ".claude",
            "{{SETTINGS_SURFACE}}": "~/.claude/settings.json and native approval rules",
        },
    },
}


class DriftError(Exception):
    pass


def load_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise DriftError(f"cannot read {path.relative_to(ROOT)}: {error}") from error
    if not isinstance(value, dict):
        raise DriftError(f"expected a JSON object in {path.relative_to(ROOT)}")
    return value


def source_path(relative: str, *, base: Path = CANONICAL) -> Path:
    candidate = (base / relative).resolve()
    if CANONICAL not in candidate.parents or not candidate.is_file():
        raise DriftError(f"invalid canonical source: {relative}")
    return candidate


def named_sources(manifest: dict[str, Any], key: str) -> list[tuple[str, Path]]:
    entries = manifest.get(key)
    if not isinstance(entries, list):
        raise DriftError(f"workflow.json field '{key}' must be a list")
    result: list[tuple[str, Path]] = []
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("id"), str):
            raise DriftError(f"workflow.json contains an invalid '{key}' entry")
        source = entry.get("source")
        if not isinstance(source, str):
            raise DriftError(f"workflow.json contains an invalid '{key}' source")
        result.append((entry["id"], source_path(source)))
    return sorted(result)


def scalar_source(manifest: dict[str, Any], key: str) -> Path:
    value = manifest.get(key)
    if not isinstance(value, dict) or not isinstance(value.get("source"), str):
        raise DriftError(f"workflow.json field '{key}' must declare a source")
    return source_path(value["source"])


def index_sources(
    manifest: dict[str, Any],
) -> tuple[
    list[Path],
    list[str],
    list[tuple[str, Path]],
    dict[str, Any],
]:
    instruction_data = manifest.get("instructions")
    if not isinstance(instruction_data, dict):
        raise DriftError("workflow.json field 'instructions' must be an object")
    raw_instructions = instruction_data.get("sources")
    if not isinstance(raw_instructions, list) or not raw_instructions:
        raise DriftError("workflow.json instructions.sources must be a non-empty list")
    if not all(isinstance(item, str) for item in raw_instructions):
        raise DriftError("workflow.json contains an invalid instruction source")
    instructions = [source_path(item) for item in raw_instructions]
    markers = instruction_data.get("preserve_markers", [])
    if not isinstance(markers, list) or not all(
        isinstance(item, str) for item in markers
    ):
        raise DriftError("workflow.json contains invalid preserve_markers")
    skills = named_sources(manifest, "skills")
    agents = named_sources(manifest, "agents")
    if agents:
        raise DriftError("this standalone checker does not render project agents")
    profiles = scalar_source(manifest, "capability_profiles")
    concerns = scalar_source(manifest, "provider_concerns")
    runtime_policy = scalar_source(manifest, "runtime_policy")
    overlays = manifest.get("native_overlays")
    if not isinstance(overlays, dict):
        raise DriftError("workflow.json field 'native_overlays' must be an object")
    overlay_sources: list[tuple[str, Path]] = []
    for provider in ("claude", "codex"):
        entry = overlays.get(provider)
        if not isinstance(entry, dict) or not isinstance(entry.get("source"), str):
            raise DriftError(f"workflow.json must declare native_overlays.{provider}")
        overlay_sources.append((provider, source_path(entry["source"])))
    metadata = {
        "schema_version": manifest.get("schema_version"),
        "instructions": [
            item.relative_to(CANONICAL).as_posix() for item in instructions
        ],
        "skills": [
            {"id": item_id, "source": path.relative_to(CANONICAL).as_posix()}
            for item_id, path in skills
        ],
        "agents": [],
        "capability_profiles": profiles.relative_to(CANONICAL).as_posix(),
        "provider_concerns": concerns.relative_to(CANONICAL).as_posix(),
        "runtime_policy": runtime_policy.relative_to(CANONICAL).as_posix(),
        "native_overlays": [
            {"provider": provider, "source": path.relative_to(CANONICAL).as_posix()}
            for provider, path in overlay_sources
        ],
        "preserve_markers": markers,
    }
    all_paths = {profiles, concerns, runtime_policy, *instructions}
    for _, skill in skills:
        all_paths.add(skill)
        for candidate in skill.parent.rglob("*"):
            if candidate.is_symlink():
                raise DriftError(
                    f"symlinked skill resource is not allowed: {candidate.relative_to(ROOT)}"
                )
            if candidate.is_file():
                all_paths.add(candidate)
    for _, overlay in overlay_sources:
        all_paths.add(overlay)
        overlay_data = load_json(overlay)
        files = overlay_data.get("files", [])
        if not isinstance(files, list):
            raise DriftError(f"invalid files list in {overlay.relative_to(ROOT)}")
        for entry in files:
            if not isinstance(entry, dict) or not isinstance(entry.get("source"), str):
                raise DriftError(f"invalid file source in {overlay.relative_to(ROOT)}")
            all_paths.add(source_path(entry["source"], base=overlay.parent))
    bundle = {"metadata": metadata, "paths": all_paths}
    return instructions, markers, skills, bundle


def canonical_hash(metadata: dict[str, Any], paths: set[Path]) -> str:
    digest = hashlib.sha256()
    normalized = json.dumps(metadata, sort_keys=True, separators=(",", ":")).encode()
    digest.update(len(normalized).to_bytes(8, "big"))
    digest.update(normalized)
    for path in sorted(paths, key=lambda item: item.relative_to(CANONICAL).as_posix()):
        relative = path.relative_to(CANONICAL).as_posix().encode()
        content = path.read_bytes()
        digest.update(len(relative).to_bytes(4, "big"))
        digest.update(relative)
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
    return digest.hexdigest()


def render_provider(content: str, provider: str) -> str:
    for token, replacement in PROVIDERS[provider]["replacements"].items():
        content = content.replace(token, replacement)
    if re.search(r"\{\{[A-Z_]+\}\}", content):
        raise DriftError(f"unknown provider placeholder in {provider} output")
    return content


def marker_line(source_hash: str, version: str) -> str:
    return f"<!-- Generated by ai-workflow {version}; source-sha256: {source_hash} -->"


def marked(
    content: str, source_hash: str, version: str, *, frontmatter: bool = False
) -> str:
    normalized = content.rstrip() + "\n"
    marker = marker_line(source_hash, version)
    if frontmatter and normalized.startswith("---\n"):
        boundary = normalized.find("\n---\n", 4)
        if boundary == -1:
            raise DriftError("canonical skill has malformed YAML frontmatter")
        insertion = boundary + len("\n---\n")
        return normalized[:insertion] + f"\n{marker}\n" + normalized[insertion:]
    return f"{marker}\n\n{normalized}"


def strip_preserved(content: str, markers: list[str]) -> str:
    lines = content.splitlines(keepends=True)
    removed: set[int] = set()
    for item in markers:
        begin = f"<!-- BEGIN:{item} -->"
        end = f"<!-- END:{item} -->"
        starts = [
            index for index, line in enumerate(lines) if line.rstrip("\r\n") == begin
        ]
        ends = [index for index, line in enumerate(lines) if line.rstrip("\r\n") == end]
        if not starts and not ends:
            continue
        if len(starts) != 1 or len(ends) != 1 or starts[0] >= ends[0]:
            raise DriftError(f"malformed preserved marker pair: {item}")
        removed.update(range(starts[0], ends[0] + 1))
    return (
        "".join(
            line for index, line in enumerate(lines) if index not in removed
        ).rstrip()
        + "\n"
    )


def assert_equal(
    path: Path, expected: str, *, markers: list[str] | None = None
) -> None:
    try:
        actual = path.read_text(encoding="utf-8")
    except OSError as error:
        raise DriftError(f"cannot read {path.relative_to(ROOT)}: {error}") from error
    if markers:
        actual = strip_preserved(actual, markers)
    if actual != expected:
        raise DriftError(f"generated file is stale: {path.relative_to(ROOT)}")


def verify() -> None:
    manifest = load_json(CANONICAL / "workflow.json")
    instructions, markers, skills, index = index_sources(manifest)
    source_hash = canonical_hash(index["metadata"], index["paths"])
    try:
        first_line = (ROOT / "AGENTS.md").read_text(encoding="utf-8").splitlines()[0]
    except (OSError, IndexError) as error:
        raise DriftError(f"cannot read AGENTS.md generator marker: {error}") from error
    match = MARKER_RE.fullmatch(first_line)
    if match is None:
        raise DriftError("AGENTS.md has no valid generator marker")
    version = match.group(1)
    instruction_text = (
        "\n\n".join(path.read_text(encoding="utf-8").rstrip() for path in instructions)
        + "\n"
    )
    for provider, config in PROVIDERS.items():
        body = (
            "@AGENTS.md\n"
            if provider == "claude" and markers
            else render_provider(instruction_text, provider)
        )
        assert_equal(
            config["instruction"],
            marked(body, source_hash, version),
            markers=markers if provider == "codex" else None,
        )
        for skill_id, source in skills:
            target = config["skills"] / skill_id
            assert_equal(
                target / "SKILL.md",
                marked(
                    render_provider(source.read_text(encoding="utf-8"), provider),
                    source_hash,
                    version,
                    frontmatter=True,
                ),
            )
            for resource in source.parent.rglob("*"):
                if resource.is_file() and resource != source:
                    relative = resource.relative_to(source.parent)
                    assert_equal(
                        target / relative,
                        resource.read_text(encoding="utf-8").rstrip() + "\n",
                    )


def main() -> int:
    try:
        verify()
    except DriftError as error:
        sys.stderr.write(
            f"AI workflow drift: {error}\n"
            "Regenerate both project providers with ai-workflow before committing.\n"
        )
        return 1
    sys.stdout.write("AI workflow generated surfaces match the canonical bundle.\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
